name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - run: bundle config set rubygems.pkg.github.com namratajha:${{ secrets.PAT }}
      - run: bundle -V
